### ISSUE TITLE
Bar does not move correctly when step size is non zero

### ISSUE THREAD

**Issue by crashmatt** [MenxLi/tkSliderWidget#5]
Using float for int means the steps are not exactly at the integer value.
1. Make the slider step to the next value when movement is 75% away
2. round the position value to the nearest step

Modify _MoveBar 

        if self.step_size > 0:
            curr_pos = self.bars[idx]["Pos"]
            if abs(curr_pos - pos) < (self.step_size * 0.75):
                return
            pos = round(pos / self.step_size) * self.step_size
        self.__moveBar(idx, pos)

Also make STEP_SIZE a variable as self.step_size.

**Comment by MenxLi** [comment]
Thanks for your suggestions, 
I have made the relative changes in 4b720b267c0fb86c7c28d2ef7e052a7109287093 and de5c80154399571b1abfc1a3bff80557246aa4a7

**Comment by MenxLi** [comment]
Thanks for your code and I just did this myself, feel free to make pull requests in the future!
